### ISSUE TITLE
dictionary generation

### ISSUE THREAD

**Issue by alessio31183** [jgeisler0303/CANFestivino#5]
First of all thanks for the effort to make this possible :)

Second: I'm not able to open objdictgen.py.
After the command: alessio@alessio-VGN-NS21M-W:~/Documents/Lavoro/UNIBS/CANBUS/CANOPEN/Firmware/CANFestivino/objdictgen$ python objdictgen.py Node.od Node.c
Traceback (most recent call last):
  File "objdictgen.py", line 27, in <module>
    from nodemanager import *
  File "/home/alessio/Documents/Lavoro/UNIBS/CANBUS/CANOPEN/Firmware/CANFestivino/objdictgen/nodemanager.py", line 24, in <module>
    from gnosis.xml.pickle import *

ImportError: No module named gnosis.xml.pickle

I got an error like: "No module named gnosis.xml.pickle"

I'm using Ubuntu 16.04 (64 bits)

Thanks in advance

Alessio

**Comment by jgeisler0303** [comment]
I guess you need to install some additional python package. I suggest you google for "gnosis python package"

**Comment by alessio31183** [comment]
Yes thanks, 
gnosis was missing

cd /tmp
wget http://gnosis.cx/download/Gnosis_Utils.More/Gnosis_Utils-1.2.2.tar.gz
tar xzf Gnosis_Utils-1.2.2.tar.gz
cd Gnosis_Utils-1.2.2/
sudo python setup.py install_all

**Comment by Jaydeep386** [comment]
C:\Users\user\Python\Scripts\python.exe C:/Users/user/Desktop/CanFestival-3/objdictgen/objdictedit.py
C:\Users\user\Desktop\CanFestival-3\objdictgen\objdictedit.py:38: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import long
C:\Users\user\Desktop\CanFestival-3\objdictgen\objdictedit.py:59: wxPyDeprecationWarning: Using deprecated class PySimpleApp. Use :class:`App` instead.
  app = wx.PySimpleApp()
Traceback (most recent call last):
  File "C:\Users\user\Desktop\CanFestival-3\objdictgen\objdictedit.py", line 86, in <module>
    from nodemanager import *
  File "C:\Users\user\Desktop\CanFestival-3\objdictgen\nodemanager.py", line 24, in <module>
    from gnosis.xml.pickle import *
  File "C:\Users\user\Python\lib\site-packages\gnosis\__init__.py", line 4, in <module>
    d = s.join(s.split(__file__, sep)[:-1], sep)+sep
AttributeError: module 'string' has no attribute 'join'

Process finished with exit code 1

**Comment by jgeisler0303** [comment]
I'm afraid that fixing this would take me too long.

I'm not using this anymore, sorry.

 Feel free to fork, fix and send me a pull request.
